spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/coway
    username: sa
    password:
    driver-class-name: org.h2.Driver
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      #ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug