spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.c8vyzmhshbnt.ap-northeast-2.rds.amazonaws.com:3306/coway?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Seoul
    username: admin
    password: bumhee0607!
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      #ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

# ResponseStatusException 을 반환할 때 포함할 내용을 설정합니다.
server:
  error:
    include-exception: true
    include-message: always
    include-stacktrace: always

logging.level:
  org.hibernate.SQL: debug